#!/bin/bash

show_banner() {
  echo ""
	echo "  _____   __                __        ___            "
	echo " / ___/  / / ___  __ __ ___/ / ____  / _ ) ___  __ __"
	echo "/ /__   / / / _ \/ // // _  / /___/ / _  |/ _ \ \ \ /"
	echo "\___/  /_/  \___/\_,_/ \_,_/       /____/ \___//_\_\ "
	echo "                                                     "
	echo "                                                     "
	echo "*********************************************************"
	echo "              Welcome to Cloud-Box utility              "
	echo "*********************************************************"
	echo ""
	echo "You can perform the following operations:"
	echo "    list               - List all files in your space"
	echo "    upload <file>      - Upload a file to your space"
	echo "    download <file>    - Download a file from your space"
	echo "    delete <file>      - Delete a file from your space"
	echo "    exit               - Exit the program"
	echo ""
}

get_user() {
  local arn
	arn=$(aws sts get-caller-identity --query "Arn" --output text)
	if [ $? -ne 0 ]; then
		echo "Failed to retrieve AWS user information."
		echo "Please ensure that your AWS CLI is properly configured for default profile and try again."
		exit 1
  fi
	USER=$(echo "$arn" | awk -F'/' '{print $NF}')
	BUCKET="s3://$BUCKET_NAME/$USER/"
}

list_objects() {
  local list
	list=$(aws s3 ls "$BUCKET" | sed '1d')
	echo "$list"
}

check_file() {

  local list
  FLAG=false
  list=$(list_objects | awk '{print $4}')
  while IFS= read -r line; do
    if [ "$line" = "$FILE" ];then
      FLAG=true
      break
    fi
  done < <(echo "$list")
}

upload_file() {

	if [ -f "$FILE" ];then
	  aws s3 cp "$FILE" "$BUCKET" > /dev/null
	  echo "$FILE was successfully uploaded"
	else
	  echo "File $FILE does not exist / Not a regular file"
	fi
}

download_file() {

  check_file
  if $FLAG;then
    aws s3 cp "$BUCKET$FILE" . >/dev/null
    echo "$FILE successfully downloaded in current dir"
  else
    echo "File $FILE not found"
  fi
}

delete_file() {

  check_file
  if $FLAG;then
    aws s3 rm "$BUCKET$FILE" >/dev/null
    echo "$FILE was successfully deleted"
  else
    echo "File $FILE not found"
  fi
}

main() {

  if [ -z "$BUCKET_NAME" ];then
    echo "BUCKET_NAME is not set. Please export correct bucket and try again"
    exit 1
  else
    aws s3api head-bucket --bucket "$BUCKET_NAME" >/dev/null 2>&1
    if [ $? -ne 0 ];then
      echo "Incorrect BUCKET_NAME. Please export correct bucket"
      exit 1
    fi

  fi

  get_user
  show_banner

  while true; do

    INPUT=''; FILE=''

    read -p "Enter: " -r INPUT FILE

    if [ "$INPUT" = "list" ];then
      echo "Listing all files..."
      list_objects
    elif [ "$INPUT" = "upload" ];then
      if [ -z "$FILE" ];then
        echo "No file specified"
      else
        echo "Uploading $FILE..."
        upload_file
      fi
    elif [ "$INPUT" = "download" ];then
      echo "Downloading $FILE..."
      download_file
    elif [ "$INPUT" = "delete" ];then
      echo "Deleting $FILE..."
      delete_file
    elif [ "$INPUT" = "exit" ];then
      echo "Exiting"
      exit 0
    else
      echo "Invalid command. Please try again"
    fi
    echo -e "_________________________________________________________\n"
  done
}

main