#!/bin/bash

show_banner() {
	echo "  _____   __                __        ___            "
	echo " / ___/  / / ___  __ __ ___/ / ____  / _ ) ___  __ __"
	echo "/ /__   / / / _ \/ // // _  / /___/ / _  |/ _ \ \ \ /"
	echo "\___/  /_/  \___/\_,_/ \_,_/       /____/ \___//_\_\ "
	echo "                                                     "
	echo "                                                     "
	echo "*******************************************************"
	echo "                                                     "
	echo "              Welcome to Cloud-Box utility              "
}

#show_usage() {
#	echo "             Usage: cloud-box [option] [file]               "
#	echo "Options: "
#	echo "   -u,  --upload        Upload a file"
#	echo "   -d,  --download      Download a file"
#	echo "   -r,  --remove        Remove a file"
#}

show_instructions() {
	echo "Operations:"
	echo "    list               List all files in your space"
	echo "    upload <file>      Upload a file to your space"
	echo "    download <file>    Download a file from your space"
	echo "    delete <file>      Delete a file from your space"
	echo "    exit               Exit the program"
}

get_user() {
  local arn
	arn=$(aws sts get-caller-identity --query "Arn" --output text)
	 if [ $? -ne 0 ]; then
		echo "Failed to retrieve AWS user information."
		exit 1
    fi
	USER=$(echo "$arn" | awk -F'/' '{print $NF}')
	BUCKET="s3://cloud-storage-891377355669/$USER/"
}

list_objects() {
  local out list
	out=$(aws s3 ls "$BUCKET")
	list=$(echo "$out" | sed '1d')
	echo "$list"
	echo "*******************************************************"
}

upload_file() {
  local file_path=$1

	if [ -f "$file_path" ]
	then
	  aws s3 cp "$file_path" "$BUCKET"
	  echo "$file_path uploaded to $BUCKET"
	else
	  echo "File does not exist/Not a regular file"
	  exit 1
	fi
}

#download_file() {
#
#}

delete_file() {

  local out list flag=false
  list=$(list_objects | sed '$d' | awk '{print $4}')
  echo "$list" | while IFS= read -r line
  do
    if [ "$line" = "$FILE" ]
    then
      aws s3 rm "$BUCKET$FILE"
      echo "$FILE was successfully deleted"
      flag=true
      break
    fi
  done
  if ! $flag;then
    echo "File not found"
  fi
}


main() {
  get_user
  show_banner
  while true; do
    INPUT=''
    FILE=''
    show_instructions
    read -r INPUT FILE
    echo "$INPUT"
    echo "$FILE"

    if [ "$INPUT" = "list" ]
    then
      echo "Files:"
      list_objects
    elif [ "$INPUT" = "upload" ]
    then
      if [ -z "$FILE" ]
      then
        echo "No file specified"
      else
        echo "Uploading $FILE"
        upload_file "$FILE"
      fi
    elif [ "$INPUT" = "download" ]
    then
      echo "Downloading $FILE"
      download_file "$FILE"
    elif [ "$INPUT" = "delete" ]
    then
      echo "Deleting $FILE"
      delete_file "$FILE"
    elif [ "$INPUT" = "exit" ]
    then
      exit 0
    else
      echo "Invalid option. Please try again."
      echo ""
    fi
  done

}

main